export const images = {
  app_logo: require('./app_logo/app_logo.png'),
  back_arrow: require('./back_arrow/back_arrow.png'),
  password_hide: require('./password_hide/password_hide.png'),
  password_show: require('./password_show/password_show.png'),
  icon_watch: require('./icon_watch/icon_watch.png'),
  icon_calender: require('./icon_calender/icon_calender.png'),
  checked: require('./checked/checked.png'),
  unchecked: require('./uncheck/uncheck.png'),
  blue_cross_icon: require('./blue_cross_icon/blueCrossIcon.png'),
  correct_icon: require('./correct_icon/correct_icon.png'),
  profile_icon: require('./profile/profile.png'),
  schedule_icon: require('./schedule/schedule.png'),
  community_icon: require('./community/community.png'),
  iconBigError: require('./icon-big-error/icon-big-error.png'),
  iconVideo: require('./video_icon/video_icon.png'),
  iconRepeat: require('./repeat_icon/repeat_icon.png'),
  iconThreeDots: require('./three_dots_icon/three_dots.png'),
  round_app_logo: require('./round_app_logo/round_app_logo.png'),
  cancle: require('./cancle/cancle.png'),
  vector: require('./vector/vector.png'),
  face: require('./face/face.png'),
  arrow_down: require('./arrow_down/arrow_down.png'),
  arrow_right: require('./arrow_right/arrow_right.png'),
  card_front: require('./card_front/card_front.png'),
  card_back: require('./card_back/card_back.png'),
};
